// <auto-generated />
using CarBackend.Data.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace CarBackend.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251125154803_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CarBackend.Core.Models.TrafficRecords", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Bus_count")
                        .HasColumnType("integer");

                    b.Property<int>("Total_vehicles")
                        .HasColumnType("integer");

                    b.Property<int>("Truck_count")
                        .HasColumnType("integer");

                    b.Property<string>("camera_Id")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("car_count")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("trafficRecords");
                });
#pragma warning restore 612, 618
        }
    }
}
